<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="MQTTnet" Version="4.3.6.1152" />
    <PackageReference Include="DotNetty.Transport" Version="0.7.5" />
    <PackageReference Include="DotNetty.Codecs" Version="0.7.5" />
    <PackageReference Include="DotNetty.Handlers" Version="0.7.5" />
    <PackageReference Include="DotNetty.Buffers" Version="0.7.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RadarSystem.Core\RadarSystem.Core.csproj" />
    <ProjectReference Include="..\RadarSystem.Data\RadarSystem.Data.csproj" />
  </ItemGroup>

</Project>
